---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: microservice-serviceclient-svc
  name: microservice-serviceclient-svc
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: microservice-serviceclient-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: microservice-serviceclient-svc
    spec:
      containers:
      - name: microservice-serviceclient-svc
        image: docker.io/alexchacon/microservice-serviceclient
        imagePullPolicy: IfNotPresent
        env:
          - name: API_QUEUE
            value: "192.168.50.4"
          - name: DATABASE_URL
            value: "postgresql://vagrant:vagrant@192.168.50.9:5432/marketplace"
        ports:
        - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: microservice-serviceclient-svc
  name: microservice-serviceclient-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3002
  selector:
    run: microservice-serviceclient-svc
  sessionAffinity: None
  type: LoadBalancer